# Generated by Django 4.2 on 2025-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_mynotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
