# Generated by Django 4.2 on 2025-12-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
