# Generated by Django 4.2 on 2025-12-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0005_usersignup_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
