# Generated by Django 4.2 on 2025-12-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_alter_usersignup_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
